### ISSUE TITLE
Missing solution for LRU Cache

### ISSUE THREAD

**Issue by OmarShawky1** [cs-MohamedAyman/Problem-Solving-Training#104]
https://github.com/cs-MohamedAyman/Problem-Solving-Training/blob/2f14673fcdb76a7a088b204cc1ee3a27d40f6b32/level-3/leetcode/interviews-questions-2/README.md?plain=1#L239

Solution for LRU Cache for Python and CPP is missing. 

Here is a GfG [C++ and Python Solution](https://www.geeksforgeeks.org/design-a-data-structure-for-lru-cache/) and here is [my enhanced Java solution](https://github.com/OmarShawky1/Problem-Solving-Map/blob/main/linkedList/LRUCache.java).

**Comment by cs-MohamedAyman** [comment]
There is no solution for any problem.
